### ISSUE TITLE
Error in dataset

### ISSUE THREAD

**Issue by mjpost** [pmichel31415/mtnt#3]
Hi,

Thanks for releasing this data! It seems that line 987 of MTNT/test/test.fr-en.tsv contains only a single tab character:

    mid 987 MTNT/test/test.fr-en.tsv | cut -f3  # → prints a blank line

The line is this one:

    11275	Atterré, confus, choqué que cela se passe sur un média de gauche, Daniel Schneiderman enfile son costume de social justice warrior. Appalled, confused, shocked that it happens on this leftist media, Daniel Schneiderman puts on his social justice warrior costume.

I am trying to add this dataset to [sacrebleu](https://github.com/mjpost/sacreBLEU) for easy downloading, but this line hoses the processing. AFAIK, this is the only line in the dataset with a problem.

**Comment by pmichel31415** [comment]
Thanks for flagging @mjpost I'll take a look

**Comment by mjpost** [comment]
Thanks! (I would have just issued a PR but it seems the data isn't in the repo...)

**Comment by pmichel31415** [comment]
Alright I have released a new version of the data including the fix: https://github.com/pmichel31415/mtnt/releases/tag/v1.1

The link on the MTNT website as well as the checksum should also be up to date now: http://www.cs.cmu.edu/~pmichel1/mtnt/

**Comment by pmichel31415** [comment]
EDIT: so to be clear the new URL to download the dataset is https://github.com/pmichel31415/mtnt/releases/download/v1.1/MTNT.1.1.tar.gz

**Comment by mjpost** [comment]
Awesome, thanks for moving so fast! This is [in sacrebleu now](https://github.com/mjpost/sacreBLEU/commit/c709e50d217d78f92869f8d42b1acdeafd2cbada), e.g.,

    sacrebleu -t mtnt1.1/test -l ja-en --echo src | head

**Comment by pmichel31415** [comment]
Awesome thanks!
